import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import ThemeProvider from '@/context/ThemeProvider';
import Header from '@/components/Header';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
        <Header/>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
